<?php

namespace App\Exports;

use App\Models\Employer;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;
use Carbon\Carbon;

class EmployerExport implements FromCollection, WithHeadings, WithMapping
{
    public function collection()
    {
        return Employer::all();
    }

    public function headings(): array
    {
        return [
            'ID', 'Company Name', 'Contact Person', 'Contact Email', 'Contact Mobile','Payment Status',
        'Transaction ID',
            'Min. Travel Trade Experience (Years)',
            'Desired Domestic Travel Expertise', 'Desired Hotel & Car Hire Expertise',
            'Desired International Travel Expertise', 'Desired Visa Handling Expertise',
            'Desired Tours & Packages Expertise', 'Desired Accounting Expertise',
            'Domestic GDS Itinerary', 'Domestic PNR Adult', 'Domestic PNR Child/Infant',
            'Domestic Senior Citizen Fares', 'Domestic Student Fares', 'Domestic Youth Special Fares',
            'Domestic Fare Mask', 'Domestic Ticketing GDS', 'Domestic GDS Type', 'Domestic LCC Websites',
            'Domestic Supplier Portal', 'Domestic Supplier Portal Name',
            'Hotel Bookings India', 'Hotel Contact Direct', 'Hotel Consolidator Websites',
            'Hotel Local DMC', 'Car Hire City', 'Car Hire Other Cities',
            'Intl GDS Itinerary', 'Intl PNR Child/Infant', 'Intl Senior Citizen Fares',
            'Intl Student Fares', 'Intl Youth Special Fares', 'Intl Fare Mask',
            'Intl GDS Type', 'Intl Queue PNRs', 'Intl First Reissue', 'Intl Subsequent Reissue',
            'Intl Ticket Refunds', 'Intl HOTAC Rooms', 'Intl Group PNR', 'Intl Issue EMD',
            'Intl Standalone EMD', 'Intl Associated EMD','Intl Mng Queues Upd PNRs',
            'Visa Aware Procedures', 'Visa Handled Personally', 'Visa In Department',
            'Visa USA', 'Visa Canada', 'Visa Mexico', 'Visa Brazil',
            'Visa Other South America', 'Visa UK', 'Visa Ireland', 'Visa Haj/Umrah',
            'Visa UAE', 'Visa Schengen Countries', 'Visa Russia', 'Visa China',
            'Visa Vietnam', 'Visa Cambodia', 'Visa Hongkong', 'Visa Philippines',
            'Visa Singapore', 'Visa Malaysia', 'Visa Australia', 'Visa New Zealand',
            'Visa Draft Cover Note',
            'Tours Handled Packages', 'Tours Countries', 'Tours Worked on Costing',
            'Tours Incentive Groups', 'Tours MICE Groups', 'Tours Cruise Passengers',
            'Acc Record Transactions', 'Acc Bank/CC Reconciliation', 'Acc Corporate Card Reconciliation',
            'Acc Track Commissions', 'Acc Submit Invoices', 'Acc Manage Financial Records',
            'Acc Software/Excel Proficient', 'Acc Prepare/Analyze Reports', 'Acc Ensure Compliance',
            'Acc Manage AP/AR', 'Acc Process Payroll/Expenses', 'Acc Calculate/Pay Taxes',
            'Acc Coordinate Auditors', 'Acc Monitor Cashflow/Forecast', 'Acc Reconcile BSP',
            'Customs Documentation Knowledge', 'IATA DG Certification', 'Airline Negotiation',
            'Air Waybill Execution', 'Regulations Compliance', 'Shipping Bill Knowledge',
            'Pharma Shipment Handling', 'Live Animal Handling', 'Perishable Shipment Handling',
            'Incoterms Knowledge',
            'Created At', 'Updated At',
        ];
    }

    public function map($employer): array
    {
        return [
            $employer->id,
            $employer->company_name,
            $employer->contact_person,
            $employer->contact_email,
            $employer->contact_mobile,
            $employer->payment_status ?? 'N/A',
    $employer->transaction_id ?? 'N/A',
            $employer->min_travel_trade_experience_years,
            $employer->desired_domestic_travel_expertise ? 'Yes' : 'No',
            $employer->desired_hotel_car_hire_expertise ? 'Yes' : 'No',
            $employer->desired_international_travel_expertise ? 'Yes' : 'No',
            $employer->desired_visa_handling_expertise ? 'Yes' : 'No',
            $employer->desired_tours_holiday_packages_expertise ? 'Yes' : 'No',
            $employer->desired_accounting_expertise ? 'Yes' : 'No',
            $employer->domestic_gds_itinerary ? 'Yes' : 'No',
            $employer->domestic_pnr_adult ? 'Yes' : 'No',
            $employer->domestic_pnr_child_infant ? 'Yes' : 'No',
            $employer->domestic_senior_citizen_fares ? 'Yes' : 'No',
            $employer->domestic_student_fares ? 'Yes' : 'No',
            $employer->domestic_youth_special_fares ? 'Yes' : 'No',
            $employer->domestic_fare_mask ? 'Yes' : 'No',
            $employer->domestic_ticketing_gds ? 'Yes' : 'No',
            $employer->domestic_gds_type,
            $employer->domestic_lcc_websites ? 'Yes' : 'No',
            $employer->domestic_supplier_portal ? 'Yes' : 'No',
            $employer->domestic_supplier_portal_name,
            $employer->hotel_bookings_india ? 'Yes' : 'No',
            $employer->hotel_contact_direct ? 'Yes' : 'No',
            $employer->hotel_consolidator_websites ? 'Yes' : 'No',
            $employer->hotel_local_dmc ? 'Yes' : 'No',
            $employer->car_hire_city ? 'Yes' : 'No',
            $employer->car_hire_other_cities ? 'Yes' : 'No',
            $employer->intl_gds_itinerary ? 'Yes' : 'No',
            $employer->intl_pnr_child_infant ? 'Yes' : 'No',
            $employer->intl_senior_citizen_fares ? 'Yes' : 'No',
            $employer->intl_student_fares ? 'Yes' : 'No',
            $employer->intl_youth_special_fares ? 'Yes' : 'No',
            $employer->intl_fare_mask ? 'Yes' : 'No',
            $employer->intl_gds_type,
            $employer->intl_queue_pnrs ? 'Yes' : 'No',
            $employer->intl_first_reissue ? 'Yes' : 'No',
            $employer->intl_subsequent_reissue ? 'Yes' : 'No',
            $employer->intl_ticket_refunds ? 'Yes' : 'No',
            $employer->intl_hotac_rooms ? 'Yes' : 'No',
            $employer->intl_group_pnr ? 'Yes' : 'No',
            $employer->intl_issue_emd ? 'Yes' : 'No',
            $employer->intl_standalone_emd ? 'Yes' : 'No',
            $employer->intl_associated_emd ? 'Yes' : 'No',
            $employer->intl_mng_queues_upd_pnrs ? 'Yes' : 'No',
            $employer->visa_aware_procedures ? 'Yes' : 'No',
            $employer->visa_handled_personally ? 'Yes' : 'No',
            $employer->visa_in_department ? 'Yes' : 'No',
            $employer->visa_usa ? 'Yes' : 'No',
            $employer->visa_canada ? 'Yes' : 'No',
            $employer->visa_mexico ? 'Yes' : 'No',
            $employer->visa_brazil ? 'Yes' : 'No',
            $employer->visa_other_south_america ? 'Yes' : 'No',
            $employer->visa_uk ? 'Yes' : 'No',
            $employer->visa_ireland ? 'Yes' : 'No',
            $employer->visa_haj_umrah ? 'Yes' : 'No',
            $employer->visa_uae ? 'Yes' : 'No',
            $employer->visa_schengen_countries,
            $employer->visa_russia ? 'Yes' : 'No',
            $employer->visa_china ? 'Yes' : 'No',
            $employer->visa_vietnam ? 'Yes' : 'No',
            $employer->visa_cambodia ? 'Yes' : 'No',
            $employer->visa_hongkong ? 'Yes' : 'No',
            $employer->visa_philippines ? 'Yes' : 'No',
            $employer->visa_singapore ? 'Yes' : 'No',
            $employer->visa_malaysia ? 'Yes' : 'No',
            $employer->visa_australia ? 'Yes' : 'No',
            $employer->visa_newzealand ? 'Yes' : 'No',
            $employer->visa_draft_cover_note ? 'Yes' : 'No',
            $employer->tours_handled_packages ? 'Yes' : 'No',
            $employer->tours_countries,
            $employer->tours_worked_cost ? 'Yes' : 'No',
            $employer->tours_incentive_groups ? 'Yes' : 'No',
            $employer->tours_mice_groups ? 'Yes' : 'No',
            $employer->tours_cruise_pax ? 'Yes' : 'No',
            $employer->acc_record_transactions ? 'Yes' : 'No',
            $employer->acc_bank_cc_reconciliation ? 'Yes' : 'No',
            $employer->acc_corporate_card_reconciliation ? 'Yes' : 'No',
            $employer->acc_track_commissions ? 'Yes' : 'No',
            $employer->acc_submit_invoices ? 'Yes' : 'No',
            $employer->acc_manage_financial_records ? 'Yes' : 'No',
            $employer->acc_software_excel_proficient ? 'Yes' : 'No',
            $employer->acc_prepare_analyze_reports ? 'Yes' : 'No',
            $employer->acc_ensure_compliance ? 'Yes' : 'No',
            $employer->acc_manage_ap_ar ? 'Yes' : 'No',
            $employer->acc_process_payroll_expenses ? 'Yes' : 'No',
            $employer->acc_calculate_pay_taxes ? 'Yes' : 'No',
            $employer->acc_coordinate_auditors ? 'Yes' : 'No',
            $employer->acc_monitor_cashflow_forecast ? 'Yes' : 'No',
            $employer->acc_reconcile_bsp ? 'Yes' : 'No',
            $employer->customs_documentation_knowledge ? 'Yes' : 'No',
            $employer->iata_dg_certification ? 'Yes' : 'No',
            $employer->airline_negotiation ? 'Yes' : 'No',
            $employer->air_waybill_execution ? 'Yes' : 'No',
            $employer->regulations_compliance ? 'Yes' : 'No',
            $employer->shipping_bill_knowledge ? 'Yes' : 'No',
            $employer->pharma_shipment_handling ? 'Yes' : 'No',
            $employer->live_animal_handling ? 'Yes' : 'No',
            $employer->perishable_shipment_handling ? 'Yes' : 'No',
            $employer->incoterms_knowledge ? 'Yes' : 'No',
            $employer->created_at ? Carbon::parse($employer->created_at)->format('d M, Y H:i:s') : null,
            $employer->updated_at ? Carbon::parse($employer->updated_at)->format('d M, Y H:i:s') : null,
        ];
    }
}
